# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'SnapchatClone' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

pod 'Firebase/Analytics'
pod 'Firebase/Auth'
pod 'Firebase/Firestore'
pod 'Firebase/Core'
pod 'Firebase/Storage'
pod 'SDWebImage', '~> 5.0'
pod 'ImageSlideshow', '~> 1.9.0'
pod "ImageSlideshow/Kingfisher"
deployment_target = '10.0'

  # Pods for SnapchatClone

end
